### PR TITLE
Test suite changes

### PR DESCRIPTION
**Pull request by fiona-gladwin**
- Use pinned memory for ROI pointers and image sizes in HIP test suite
- Minor fix : Release image sizes buffer in HOST test suite

### CODE REVIEW

**Review by r-abishek — COMMENTED** [review]
It should actually be done the other way to avoid reader confusion. 
'd_' indicates gpu or device buffers, but pinned memory is present on host RAM, not on device.

**Comment by r-abishek** [comment]
@fiona-gladwin Pls do a ToT merge. PR#130, PR#131 got merged today.

**Comment by fiona-gladwin** [comment]
@r-abishek I have merged the branch with TOT. I have removed the d_ from the variables using pinned memory, Please check

**Review by r-abishek — APPROVED** [review]
looks good, merging

**Pull request merged**
