### PR TITLE
Fix HIP testsuite

### PR DESCRIPTION
**Pull request by snehaa8**

### CODE REVIEW

**Comment by r-abishek** [comment]
@snehaa8 have you ensured the hip test suite for LUT works with and without profiling options?

**Comment by snehaa8** [comment]
without profiling it works fine, checking perf test with profiling option enabled now.

**Comment by snehaa8** [comment]
Confirmed everything works fine with testsuite.

**Review by r-abishek — APPROVED** [review]
lgtm

**Pull request merged**
